/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ACasoCasoM extends PCasoM
{
    private PCasoM _casoM_;
    private PValor _valor_;
    private PComando _comando_;

    public ACasoCasoM()
    {
        // Constructor
    }

    public ACasoCasoM(
        @SuppressWarnings("hiding") PCasoM _casoM_,
        @SuppressWarnings("hiding") PValor _valor_,
        @SuppressWarnings("hiding") PComando _comando_)
    {
        // Constructor
        setCasoM(_casoM_);

        setValor(_valor_);

        setComando(_comando_);

    }

    @Override
    public Object clone()
    {
        return new ACasoCasoM(
            cloneNode(this._casoM_),
            cloneNode(this._valor_),
            cloneNode(this._comando_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasoCasoM(this);
    }

    public PCasoM getCasoM()
    {
        return this._casoM_;
    }

    public void setCasoM(PCasoM node)
    {
        if(this._casoM_ != null)
        {
            this._casoM_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoM_ = node;
    }

    public PValor getValor()
    {
        return this._valor_;
    }

    public void setValor(PValor node)
    {
        if(this._valor_ != null)
        {
            this._valor_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._valor_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._casoM_)
            + toString(this._valor_)
            + toString(this._comando_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._casoM_ == child)
        {
            this._casoM_ = null;
            return;
        }

        if(this._valor_ == child)
        {
            this._valor_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._casoM_ == oldChild)
        {
            setCasoM((PCasoM) newChild);
            return;
        }

        if(this._valor_ == oldChild)
        {
            setValor((PValor) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
