/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ADeclM extends PDeclM
{
    private PVariavel _variavel_;
    private TVirgula _virgula_;
    private PDeclM _declM_;

    public ADeclM()
    {
        // Constructor
    }

    public ADeclM(
        @SuppressWarnings("hiding") PVariavel _variavel_,
        @SuppressWarnings("hiding") TVirgula _virgula_,
        @SuppressWarnings("hiding") PDeclM _declM_)
    {
        // Constructor
        setVariavel(_variavel_);

        setVirgula(_virgula_);

        setDeclM(_declM_);

    }

    @Override
    public Object clone()
    {
        return new ADeclM(
            cloneNode(this._variavel_),
            cloneNode(this._virgula_),
            cloneNode(this._declM_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclM(this);
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public TVirgula getVirgula()
    {
        return this._virgula_;
    }

    public void setVirgula(TVirgula node)
    {
        if(this._virgula_ != null)
        {
            this._virgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._virgula_ = node;
    }

    public PDeclM getDeclM()
    {
        return this._declM_;
    }

    public void setDeclM(PDeclM node)
    {
        if(this._declM_ != null)
        {
            this._declM_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declM_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._virgula_)
            + toString(this._declM_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._virgula_ == child)
        {
            this._virgula_ = null;
            return;
        }

        if(this._declM_ == child)
        {
            this._declM_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        if(this._virgula_ == oldChild)
        {
            setVirgula((TVirgula) newChild);
            return;
        }

        if(this._declM_ == oldChild)
        {
            setDeclM((PDeclM) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
