/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ADeclSDeclM extends PDeclM
{
    private PDeclS _declS_;

    public ADeclSDeclM()
    {
        // Constructor
    }

    public ADeclSDeclM(
        @SuppressWarnings("hiding") PDeclS _declS_)
    {
        // Constructor
        setDeclS(_declS_);

    }

    @Override
    public Object clone()
    {
        return new ADeclSDeclM(
            cloneNode(this._declS_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclSDeclM(this);
    }

    public PDeclS getDeclS()
    {
        return this._declS_;
    }

    public void setDeclS(PDeclS node)
    {
        if(this._declS_ != null)
        {
            this._declS_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._declS_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._declS_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._declS_ == child)
        {
            this._declS_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._declS_ == oldChild)
        {
            setDeclS((PDeclS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
