/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ADivMultA extends PMultA
{
    private TDivInt _divInt_;

    public ADivMultA()
    {
        // Constructor
    }

    public ADivMultA(
        @SuppressWarnings("hiding") TDivInt _divInt_)
    {
        // Constructor
        setDivInt(_divInt_);

    }

    @Override
    public Object clone()
    {
        return new ADivMultA(
            cloneNode(this._divInt_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivMultA(this);
    }

    public TDivInt getDivInt()
    {
        return this._divInt_;
    }

    public void setDivInt(TDivInt node)
    {
        if(this._divInt_ != null)
        {
            this._divInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._divInt_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._divInt_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._divInt_ == child)
        {
            this._divInt_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._divInt_ == oldChild)
        {
            setDivInt((TDivInt) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
