/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AElseSeEst extends PSeEst
{
    private PExplogica _explogica_;
    private PComando _comando_;
    private PSeSen _seSen_;

    public AElseSeEst()
    {
        // Constructor
    }

    public AElseSeEst(
        @SuppressWarnings("hiding") PExplogica _explogica_,
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") PSeSen _seSen_)
    {
        // Constructor
        setExplogica(_explogica_);

        setComando(_comando_);

        setSeSen(_seSen_);

    }

    @Override
    public Object clone()
    {
        return new AElseSeEst(
            cloneNode(this._explogica_),
            cloneNode(this._comando_),
            cloneNode(this._seSen_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAElseSeEst(this);
    }

    public PExplogica getExplogica()
    {
        return this._explogica_;
    }

    public void setExplogica(PExplogica node)
    {
        if(this._explogica_ != null)
        {
            this._explogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogica_ = node;
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public PSeSen getSeSen()
    {
        return this._seSen_;
    }

    public void setSeSen(PSeSen node)
    {
        if(this._seSen_ != null)
        {
            this._seSen_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._seSen_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explogica_)
            + toString(this._comando_)
            + toString(this._seSen_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explogica_ == child)
        {
            this._explogica_ = null;
            return;
        }

        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._seSen_ == child)
        {
            this._seSen_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explogica_ == oldChild)
        {
            setExplogica((PExplogica) newChild);
            return;
        }

        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._seSen_ == oldChild)
        {
            setSeSen((PSeSen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
