/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AEscrevaSEscrevaM extends PEscrevaM
{
    private PEscrevaS _escrevaS_;

    public AEscrevaSEscrevaM()
    {
        // Constructor
    }

    public AEscrevaSEscrevaM(
        @SuppressWarnings("hiding") PEscrevaS _escrevaS_)
    {
        // Constructor
        setEscrevaS(_escrevaS_);

    }

    @Override
    public Object clone()
    {
        return new AEscrevaSEscrevaM(
            cloneNode(this._escrevaS_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEscrevaSEscrevaM(this);
    }

    public PEscrevaS getEscrevaS()
    {
        return this._escrevaS_;
    }

    public void setEscrevaS(PEscrevaS node)
    {
        if(this._escrevaS_ != null)
        {
            this._escrevaS_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._escrevaS_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._escrevaS_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._escrevaS_ == child)
        {
            this._escrevaS_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._escrevaS_ == oldChild)
        {
            setEscrevaS((PEscrevaS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
