/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AExp6TermoExp extends PTermoExp
{
    private PTermoExp _termoExp_;
    private TMaiorQue _maiorQue_;
    private PExpA _expA_;

    public AExp6TermoExp()
    {
        // Constructor
    }

    public AExp6TermoExp(
        @SuppressWarnings("hiding") PTermoExp _termoExp_,
        @SuppressWarnings("hiding") TMaiorQue _maiorQue_,
        @SuppressWarnings("hiding") PExpA _expA_)
    {
        // Constructor
        setTermoExp(_termoExp_);

        setMaiorQue(_maiorQue_);

        setExpA(_expA_);

    }

    @Override
    public Object clone()
    {
        return new AExp6TermoExp(
            cloneNode(this._termoExp_),
            cloneNode(this._maiorQue_),
            cloneNode(this._expA_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp6TermoExp(this);
    }

    public PTermoExp getTermoExp()
    {
        return this._termoExp_;
    }

    public void setTermoExp(PTermoExp node)
    {
        if(this._termoExp_ != null)
        {
            this._termoExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoExp_ = node;
    }

    public TMaiorQue getMaiorQue()
    {
        return this._maiorQue_;
    }

    public void setMaiorQue(TMaiorQue node)
    {
        if(this._maiorQue_ != null)
        {
            this._maiorQue_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorQue_ = node;
    }

    public PExpA getExpA()
    {
        return this._expA_;
    }

    public void setExpA(PExpA node)
    {
        if(this._expA_ != null)
        {
            this._expA_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expA_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoExp_)
            + toString(this._maiorQue_)
            + toString(this._expA_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoExp_ == child)
        {
            this._termoExp_ = null;
            return;
        }

        if(this._maiorQue_ == child)
        {
            this._maiorQue_ = null;
            return;
        }

        if(this._expA_ == child)
        {
            this._expA_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoExp_ == oldChild)
        {
            setTermoExp((PTermoExp) newChild);
            return;
        }

        if(this._maiorQue_ == oldChild)
        {
            setMaiorQue((TMaiorQue) newChild);
            return;
        }

        if(this._expA_ == oldChild)
        {
            setExpA((PExpA) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
