/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AExp2TermoExp extends PTermoExp
{
    private PTermoExp _termoExp_;
    private TDiferente _diferente_;
    private PExpA _expA_;

    public AExp2TermoExp()
    {
        // Constructor
    }

    public AExp2TermoExp(
        @SuppressWarnings("hiding") PTermoExp _termoExp_,
        @SuppressWarnings("hiding") TDiferente _diferente_,
        @SuppressWarnings("hiding") PExpA _expA_)
    {
        // Constructor
        setTermoExp(_termoExp_);

        setDiferente(_diferente_);

        setExpA(_expA_);

    }

    @Override
    public Object clone()
    {
        return new AExp2TermoExp(
            cloneNode(this._termoExp_),
            cloneNode(this._diferente_),
            cloneNode(this._expA_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp2TermoExp(this);
    }

    public PTermoExp getTermoExp()
    {
        return this._termoExp_;
    }

    public void setTermoExp(PTermoExp node)
    {
        if(this._termoExp_ != null)
        {
            this._termoExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoExp_ = node;
    }

    public TDiferente getDiferente()
    {
        return this._diferente_;
    }

    public void setDiferente(TDiferente node)
    {
        if(this._diferente_ != null)
        {
            this._diferente_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._diferente_ = node;
    }

    public PExpA getExpA()
    {
        return this._expA_;
    }

    public void setExpA(PExpA node)
    {
        if(this._expA_ != null)
        {
            this._expA_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expA_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoExp_)
            + toString(this._diferente_)
            + toString(this._expA_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoExp_ == child)
        {
            this._termoExp_ = null;
            return;
        }

        if(this._diferente_ == child)
        {
            this._diferente_ = null;
            return;
        }

        if(this._expA_ == child)
        {
            this._expA_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoExp_ == oldChild)
        {
            setTermoExp((PTermoExp) newChild);
            return;
        }

        if(this._diferente_ == oldChild)
        {
            setDiferente((TDiferente) newChild);
            return;
        }

        if(this._expA_ == oldChild)
        {
            setExpA((PExpA) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
