/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AExp4TermoExp extends PTermoExp
{
    private PTermoExp _termoExp_;
    private TMaiorIgual _maiorIgual_;
    private PExpA _expA_;

    public AExp4TermoExp()
    {
        // Constructor
    }

    public AExp4TermoExp(
        @SuppressWarnings("hiding") PTermoExp _termoExp_,
        @SuppressWarnings("hiding") TMaiorIgual _maiorIgual_,
        @SuppressWarnings("hiding") PExpA _expA_)
    {
        // Constructor
        setTermoExp(_termoExp_);

        setMaiorIgual(_maiorIgual_);

        setExpA(_expA_);

    }

    @Override
    public Object clone()
    {
        return new AExp4TermoExp(
            cloneNode(this._termoExp_),
            cloneNode(this._maiorIgual_),
            cloneNode(this._expA_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp4TermoExp(this);
    }

    public PTermoExp getTermoExp()
    {
        return this._termoExp_;
    }

    public void setTermoExp(PTermoExp node)
    {
        if(this._termoExp_ != null)
        {
            this._termoExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoExp_ = node;
    }

    public TMaiorIgual getMaiorIgual()
    {
        return this._maiorIgual_;
    }

    public void setMaiorIgual(TMaiorIgual node)
    {
        if(this._maiorIgual_ != null)
        {
            this._maiorIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maiorIgual_ = node;
    }

    public PExpA getExpA()
    {
        return this._expA_;
    }

    public void setExpA(PExpA node)
    {
        if(this._expA_ != null)
        {
            this._expA_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expA_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoExp_)
            + toString(this._maiorIgual_)
            + toString(this._expA_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoExp_ == child)
        {
            this._termoExp_ = null;
            return;
        }

        if(this._maiorIgual_ == child)
        {
            this._maiorIgual_ = null;
            return;
        }

        if(this._expA_ == child)
        {
            this._expA_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoExp_ == oldChild)
        {
            setTermoExp((PTermoExp) newChild);
            return;
        }

        if(this._maiorIgual_ == oldChild)
        {
            setMaiorIgual((TMaiorIgual) newChild);
            return;
        }

        if(this._expA_ == oldChild)
        {
            setExpA((PExpA) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
