/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AFatExpXor extends PExpXor
{
    private PExplFator _explFator_;

    public AFatExpXor()
    {
        // Constructor
    }

    public AFatExpXor(
        @SuppressWarnings("hiding") PExplFator _explFator_)
    {
        // Constructor
        setExplFator(_explFator_);

    }

    @Override
    public Object clone()
    {
        return new AFatExpXor(
            cloneNode(this._explFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatExpXor(this);
    }

    public PExplFator getExplFator()
    {
        return this._explFator_;
    }

    public void setExplFator(PExplFator node)
    {
        if(this._explFator_ != null)
        {
            this._explFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explFator_ == child)
        {
            this._explFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explFator_ == oldChild)
        {
            setExplFator((PExplFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
