/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AFatTermoExpl extends PTermoExpl
{
    private PTermoExp _termoExp_;

    public AFatTermoExpl()
    {
        // Constructor
    }

    public AFatTermoExpl(
        @SuppressWarnings("hiding") PTermoExp _termoExp_)
    {
        // Constructor
        setTermoExp(_termoExp_);

    }

    @Override
    public Object clone()
    {
        return new AFatTermoExpl(
            cloneNode(this._termoExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatTermoExpl(this);
    }

    public PTermoExp getTermoExp()
    {
        return this._termoExp_;
    }

    public void setTermoExp(PTermoExp node)
    {
        if(this._termoExp_ != null)
        {
            this._termoExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoExp_ == child)
        {
            this._termoExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoExp_ == oldChild)
        {
            setTermoExp((PTermoExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
