/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AForPassoParaEst extends PParaEst
{
    private PVariavel _variavel_;
    private TNumeroInt _numeroInt_;
    private PFor2 _for2_;

    public AForPassoParaEst()
    {
        // Constructor
    }

    public AForPassoParaEst(
        @SuppressWarnings("hiding") PVariavel _variavel_,
        @SuppressWarnings("hiding") TNumeroInt _numeroInt_,
        @SuppressWarnings("hiding") PFor2 _for2_)
    {
        // Constructor
        setVariavel(_variavel_);

        setNumeroInt(_numeroInt_);

        setFor2(_for2_);

    }

    @Override
    public Object clone()
    {
        return new AForPassoParaEst(
            cloneNode(this._variavel_),
            cloneNode(this._numeroInt_),
            cloneNode(this._for2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAForPassoParaEst(this);
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public TNumeroInt getNumeroInt()
    {
        return this._numeroInt_;
    }

    public void setNumeroInt(TNumeroInt node)
    {
        if(this._numeroInt_ != null)
        {
            this._numeroInt_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numeroInt_ = node;
    }

    public PFor2 getFor2()
    {
        return this._for2_;
    }

    public void setFor2(PFor2 node)
    {
        if(this._for2_ != null)
        {
            this._for2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._for2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._numeroInt_)
            + toString(this._for2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._numeroInt_ == child)
        {
            this._numeroInt_ = null;
            return;
        }

        if(this._for2_ == child)
        {
            this._for2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        if(this._numeroInt_ == oldChild)
        {
            setNumeroInt((TNumeroInt) newChild);
            return;
        }

        if(this._for2_ == oldChild)
        {
            setFor2((PFor2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
