/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ALeiaMLeiaM extends PLeiaM
{
    private PVariavel _variavel_;
    private PLeiaM _leiaM_;

    public ALeiaMLeiaM()
    {
        // Constructor
    }

    public ALeiaMLeiaM(
        @SuppressWarnings("hiding") PVariavel _variavel_,
        @SuppressWarnings("hiding") PLeiaM _leiaM_)
    {
        // Constructor
        setVariavel(_variavel_);

        setLeiaM(_leiaM_);

    }

    @Override
    public Object clone()
    {
        return new ALeiaMLeiaM(
            cloneNode(this._variavel_),
            cloneNode(this._leiaM_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeiaMLeiaM(this);
    }

    public PVariavel getVariavel()
    {
        return this._variavel_;
    }

    public void setVariavel(PVariavel node)
    {
        if(this._variavel_ != null)
        {
            this._variavel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._variavel_ = node;
    }

    public PLeiaM getLeiaM()
    {
        return this._leiaM_;
    }

    public void setLeiaM(PLeiaM node)
    {
        if(this._leiaM_ != null)
        {
            this._leiaM_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leiaM_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._variavel_)
            + toString(this._leiaM_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._variavel_ == child)
        {
            this._variavel_ = null;
            return;
        }

        if(this._leiaM_ == child)
        {
            this._leiaM_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._variavel_ == oldChild)
        {
            setVariavel((PVariavel) newChild);
            return;
        }

        if(this._leiaM_ == oldChild)
        {
            setLeiaM((PLeiaM) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
