/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ALeiaSLeiaM extends PLeiaM
{
    private PLeiaS _leiaS_;

    public ALeiaSLeiaM()
    {
        // Constructor
    }

    public ALeiaSLeiaM(
        @SuppressWarnings("hiding") PLeiaS _leiaS_)
    {
        // Constructor
        setLeiaS(_leiaS_);

    }

    @Override
    public Object clone()
    {
        return new ALeiaSLeiaM(
            cloneNode(this._leiaS_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeiaSLeiaM(this);
    }

    public PLeiaS getLeiaS()
    {
        return this._leiaS_;
    }

    public void setLeiaS(PLeiaS node)
    {
        if(this._leiaS_ != null)
        {
            this._leiaS_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._leiaS_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._leiaS_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._leiaS_ == child)
        {
            this._leiaS_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._leiaS_ == oldChild)
        {
            setLeiaS((PLeiaS) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
