/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ANormalAvalieEst extends PAvalieEst
{
    private PExp _exp_;
    private PCasoM _casoM_;

    public ANormalAvalieEst()
    {
        // Constructor
    }

    public ANormalAvalieEst(
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") PCasoM _casoM_)
    {
        // Constructor
        setExp(_exp_);

        setCasoM(_casoM_);

    }

    @Override
    public Object clone()
    {
        return new ANormalAvalieEst(
            cloneNode(this._exp_),
            cloneNode(this._casoM_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANormalAvalieEst(this);
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public PCasoM getCasoM()
    {
        return this._casoM_;
    }

    public void setCasoM(PCasoM node)
    {
        if(this._casoM_ != null)
        {
            this._casoM_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._casoM_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp_)
            + toString(this._casoM_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._casoM_ == child)
        {
            this._casoM_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._casoM_ == oldChild)
        {
            setCasoM((PCasoM) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
