/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AOutroExplFator extends PExplFator
{
    private PExplTermo _explTermo_;

    public AOutroExplFator()
    {
        // Constructor
    }

    public AOutroExplFator(
        @SuppressWarnings("hiding") PExplTermo _explTermo_)
    {
        // Constructor
        setExplTermo(_explTermo_);

    }

    @Override
    public Object clone()
    {
        return new AOutroExplFator(
            cloneNode(this._explTermo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOutroExplFator(this);
    }

    public PExplTermo getExplTermo()
    {
        return this._explTermo_;
    }

    public void setExplTermo(PExplTermo node)
    {
        if(this._explTermo_ != null)
        {
            this._explTermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explTermo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explTermo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explTermo_ == child)
        {
            this._explTermo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explTermo_ == oldChild)
        {
            setExplTermo((PExplTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
