/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ARepitaEst extends PRepitaEst
{
    private PComando _comando_;
    private PExplogica _explogica_;

    public ARepitaEst()
    {
        // Constructor
    }

    public ARepitaEst(
        @SuppressWarnings("hiding") PComando _comando_,
        @SuppressWarnings("hiding") PExplogica _explogica_)
    {
        // Constructor
        setComando(_comando_);

        setExplogica(_explogica_);

    }

    @Override
    public Object clone()
    {
        return new ARepitaEst(
            cloneNode(this._comando_),
            cloneNode(this._explogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepitaEst(this);
    }

    public PComando getComando()
    {
        return this._comando_;
    }

    public void setComando(PComando node)
    {
        if(this._comando_ != null)
        {
            this._comando_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comando_ = node;
    }

    public PExplogica getExplogica()
    {
        return this._explogica_;
    }

    public void setExplogica(PExplogica node)
    {
        if(this._explogica_ != null)
        {
            this._explogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comando_)
            + toString(this._explogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comando_ == child)
        {
            this._comando_ = null;
            return;
        }

        if(this._explogica_ == child)
        {
            this._explogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comando_ == oldChild)
        {
            setComando((PComando) newChild);
            return;
        }

        if(this._explogica_ == oldChild)
        {
            setExplogica((PExplogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
