/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ASingleExplTermo extends PExplTermo
{
    private TNao _nao_;
    private PExplFator _explFator_;

    public ASingleExplTermo()
    {
        // Constructor
    }

    public ASingleExplTermo(
        @SuppressWarnings("hiding") TNao _nao_,
        @SuppressWarnings("hiding") PExplFator _explFator_)
    {
        // Constructor
        setNao(_nao_);

        setExplFator(_explFator_);

    }

    @Override
    public Object clone()
    {
        return new ASingleExplTermo(
            cloneNode(this._nao_),
            cloneNode(this._explFator_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseASingleExplTermo(this);
    }

    public TNao getNao()
    {
        return this._nao_;
    }

    public void setNao(TNao node)
    {
        if(this._nao_ != null)
        {
            this._nao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nao_ = node;
    }

    public PExplFator getExplFator()
    {
        return this._explFator_;
    }

    public void setExplFator(PExplFator node)
    {
        if(this._explFator_ != null)
        {
            this._explFator_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explFator_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nao_)
            + toString(this._explFator_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nao_ == child)
        {
            this._nao_ = null;
            return;
        }

        if(this._explFator_ == child)
        {
            this._explFator_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nao_ == oldChild)
        {
            setNao((TNao) newChild);
            return;
        }

        if(this._explFator_ == oldChild)
        {
            setExplFator((PExplFator) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
