/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AStartStart extends PStart
{
    private PProgramaEst _programaEst_;

    public AStartStart()
    {
        // Constructor
    }

    public AStartStart(
        @SuppressWarnings("hiding") PProgramaEst _programaEst_)
    {
        // Constructor
        setProgramaEst(_programaEst_);

    }

    @Override
    public Object clone()
    {
        return new AStartStart(
            cloneNode(this._programaEst_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStartStart(this);
    }

    public PProgramaEst getProgramaEst()
    {
        return this._programaEst_;
    }

    public void setProgramaEst(PProgramaEst node)
    {
        if(this._programaEst_ != null)
        {
            this._programaEst_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._programaEst_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._programaEst_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._programaEst_ == child)
        {
            this._programaEst_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._programaEst_ == oldChild)
        {
            setProgramaEst((PProgramaEst) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
