/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class ATerm1TermoExpl extends PTermoExpl
{
    private PTermoExpl _termoExpl_;
    private TOu _ou_;
    private PTermoExp _termoExp_;

    public ATerm1TermoExpl()
    {
        // Constructor
    }

    public ATerm1TermoExpl(
        @SuppressWarnings("hiding") PTermoExpl _termoExpl_,
        @SuppressWarnings("hiding") TOu _ou_,
        @SuppressWarnings("hiding") PTermoExp _termoExp_)
    {
        // Constructor
        setTermoExpl(_termoExpl_);

        setOu(_ou_);

        setTermoExp(_termoExp_);

    }

    @Override
    public Object clone()
    {
        return new ATerm1TermoExpl(
            cloneNode(this._termoExpl_),
            cloneNode(this._ou_),
            cloneNode(this._termoExp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATerm1TermoExpl(this);
    }

    public PTermoExpl getTermoExpl()
    {
        return this._termoExpl_;
    }

    public void setTermoExpl(PTermoExpl node)
    {
        if(this._termoExpl_ != null)
        {
            this._termoExpl_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoExpl_ = node;
    }

    public TOu getOu()
    {
        return this._ou_;
    }

    public void setOu(TOu node)
    {
        if(this._ou_ != null)
        {
            this._ou_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ou_ = node;
    }

    public PTermoExp getTermoExp()
    {
        return this._termoExp_;
    }

    public void setTermoExp(PTermoExp node)
    {
        if(this._termoExp_ != null)
        {
            this._termoExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoExp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoExpl_)
            + toString(this._ou_)
            + toString(this._termoExp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoExpl_ == child)
        {
            this._termoExpl_ = null;
            return;
        }

        if(this._ou_ == child)
        {
            this._ou_ = null;
            return;
        }

        if(this._termoExp_ == child)
        {
            this._termoExp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoExpl_ == oldChild)
        {
            setTermoExpl((PTermoExpl) newChild);
            return;
        }

        if(this._ou_ == oldChild)
        {
            setOu((TOu) newChild);
            return;
        }

        if(this._termoExp_ == oldChild)
        {
            setTermoExp((PTermoExp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
