/* This file was generated by SableCC (http://www.sablecc.org/). */

package projetolft.node;

import projetolft.analysis.*;

@SuppressWarnings("nls")
public final class AUnicaExplTermo extends PExplTermo
{
    private PExplogica _explogica_;

    public AUnicaExplTermo()
    {
        // Constructor
    }

    public AUnicaExplTermo(
        @SuppressWarnings("hiding") PExplogica _explogica_)
    {
        // Constructor
        setExplogica(_explogica_);

    }

    @Override
    public Object clone()
    {
        return new AUnicaExplTermo(
            cloneNode(this._explogica_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAUnicaExplTermo(this);
    }

    public PExplogica getExplogica()
    {
        return this._explogica_;
    }

    public void setExplogica(PExplogica node)
    {
        if(this._explogica_ != null)
        {
            this._explogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._explogica_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._explogica_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._explogica_ == child)
        {
            this._explogica_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._explogica_ == oldChild)
        {
            setExplogica((PExplogica) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
